apiVersion: v1
kind: Secret
metadata:
  name: library-secret
  namespace: library-system
  labels:
    app: library-service
type: Opaque
data:
  # echo -n "value" | base64
  DB_USER: cG9zdGdyZXM=
  DB_PASS: cG9zdGdyZXM=
  ADMIN_PASSWORD: QWRtaW4xMjM0IQ==
  JWT_SECRET: YzEwOWQxODIwYzU0NDc0ODM0NjA4OTFhNTFmN2M1MjZjYjU1YzRkN2IyZGNmNWUzYWUyMWVlNzMwYWY1ZGY4Yg==
